### PR TITLE
add intersects to Data.Set.*

### PR DESCRIPTION
**Pull request by chessai**
check whether the two sets intersect at all, without taking the intersection

### CODE REVIEW

**Comment by andrewthad** [comment]
Excellent. This is a good function to have. It’s probably worthwhile to have a test for this to make sure it matches to behavior of its counterpart from containers.

**Comment by chessai** [comment]
Okay, don't merge until that test is pushed to this branch. Don't know when I'll get to it

**Comment by andrewthad** [comment]
Oh, and you’ll probably want to throw an INLINEABLE pragma on intersects. The rule of thumb I’ve been using is that functions for constructing data structures don’t get INLINEABLE pragmas since they perform poorly regardless, but functions that read from a set do get INLINEABLE, since those are the places we expect to outperform containers.

**Comment by andrewthad** [comment]
This all looks good to me. Feel free to squash and merge.

**Pull request merged**
